name: Consider Best Stories

on:
  schedule:
    # Run the job once a day at 7:00 AM UTC
    - cron: '0 7 * * *'
  workflow_dispatch:  # This enables manual trigger

jobs:
  send_stories:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Run the script
      run: |
        source env/bin/activate
        python hn.py > stories.txt

    - name: Send Email with popular stories
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Daily Hacker News Popular Stories"
        to: ${{ secrets.EMAIL_TO }}
        from: ${{ secrets.EMAIL_FROM }}
        body: |
          **Here are the most popular Hacker News stories from the last 24 hours:**

          $(cat stories.txt)
        convert_markdown: true
